/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
 * Generated on: 29-May-2018 00:21:58
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 11
const int NL_G[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T NUM_G[MWSPT_NSEC][3] = {
  {
     0.1207782552,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.1207782552,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.1143561676,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.1143561676,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.1121602431,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
                1,              0,              0 
  }
};
const int DL_G[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T DEN_G[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.749549985,   0.8956164718 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.934163809,   0.9571841955 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.838340402,   0.8681164384 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.664800406,   0.7660372257 
  },
  {
                1,              0,              0 
  },
  {
                1,    -1.72183001,   0.7756795287 
  },
  {
                1,              0,              0 
  }
};
