/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
 * Generated on: 14-Jun-2019 14:18:55
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 3
 * Denominator Length  : 3
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s16,19 -> [-6.250000e-02 6.250000e-02)
 * Denominator         : s16,14 -> [-2 2)
 * Input               : s16,15 -> [-1 1)
 * Output              : s16,16 -> [-5.000000e-01 5.000000e-01)
 * State               : s16,15 -> [-1 1)
 * Numerator Prod      : s32,34 -> [-1.250000e-01 1.250000e-01)
 * Denominator Prod    : s32,29 -> [-4 4)
 * Numerator Accum     : s34,34 -> [-5.000000e-01 5.000000e-01)
 * Denominator Accum   : s34,29 -> [-16 16)
 * Round Mode          : convergent
 * Overflow Mode       : saturate
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2019a\extern\include\tmwtypes.h 
 */
const int NL_LPF = 3;
const int16_T NUM_LPF[3] = {
      491,    982,    491
};
const int DL_LPF = 3;
const int16_T DEN_LPF[3] = {
    16384, -23826,   9405
};
