/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
 * Generated on: 29-May-2018 00:21:27
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 11
const int NL_B[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T NUM_B[MWSPT_NSEC][3] = {
  {
     0.0421603173,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.0421603173,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
    0.04131028056,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
    0.04131028056,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.0409989059,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
                1,              0,              0 
  }
};
const int DL_B[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T DEN_B[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.942678332,   0.9642475247 
  },
  {
                1,              0,              0 
  },
  {
                1,    -1.97940433,   0.9837804437 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.900575042,   0.9166212678 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.944389701,   0.9500371814 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.908554435,   0.9180021882 
  },
  {
                1,              0,              0 
  }
};
