/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
 * Generated on: 10-Dec-2017 12:18:18
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 7
 * Denominator Length  : 7
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int NL_R = 7;
const real32_T NUM_R[7] = {
  1.018241983e-05,              0,-3.054725676e-05,              0,3.054725676e-05,
                0,-1.018241983e-05
};
const int DL_R = 7;
const real32_T DEN_R[7] = {
                1,   -5.904019833,    14.53243637,   -19.08894539,    14.11244678,
     -5.567705631,   0.9157868028
};
