/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
 * Generated on: 28-May-2018 18:21:46
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 11
const int NL_T[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T NUM_T[MWSPT_NSEC][3] = {
  {
    0.01002184395,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
    0.01002184395,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
   0.009972155094,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
   0.009972155094,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
   0.009953369386,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
                1,              0,              0 
  }
};
const int DL_T[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T DEN_T[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.990267754,   0.9918315411 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.995369911,    0.995785296 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.979255795,   0.9804859161 
  },
  {
                1,              0,              0 
  },
  {
                1,    -1.98673296,   0.9872556925 
  },
  {
                1,              0,              0 
  },
  {
                1,    -1.97929287,   0.9800932407 
  },
  {
                1,              0,              0 
  }
};
