/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
 * Generated on: 29-May-2018 00:20:52
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 11
const int NL_A[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T NUM_A[MWSPT_NSEC][3] = {
  {
    0.01002184395,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
    0.01002184395,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
   0.009972155094,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
   0.009972155094,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
   0.009953369386,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
                1,              0,              0 
  }
};
const int DL_A[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T DEN_A[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.989073038,     0.99262923 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.993341565,    0.994985044 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.978873014,   0.9819360375 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.983908534,   0.9857977629 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.977692246,   0.9800932407 
  },
  {
                1,              0,              0 
  }
};
