/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
 * Generated on: 29-May-2018 00:20:12
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 11
const int NL_D[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T NUM_D[MWSPT_NSEC][3] = {
  {
   0.007522245403,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
   0.007522245403,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
   0.007494178135,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
   0.007494178135,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
   0.007483539637,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
                1,              0,              0 
  }
};
const int DL_D[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T DEN_D[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.992241979,   0.9926296473 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.998053789,   0.9980800748 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.982032776,   0.9823058844 
  },
  {
                1,              0,              0 
  },
  {
                1,    -1.99343729,   0.9934742451 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.984932661,   0.9850329161 
  },
  {
                1,              0,              0 
  }
};
