/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 10-Jan-2024 17:13:06
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 2
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2021b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 5
const int NL_R1[MWSPT_NSEC] = { 1,3,1,3,1 };
const real32_T NUM_R1[MWSPT_NSEC][3] = {
  {
     0.2597215176,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.2597215176,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
                1,              0,              0 
  }
};
const int DL_R1[MWSPT_NSEC] = { 1,3,1,3,1 };
const real32_T DEN_R1[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.308020353,   0.6975045204 
  },
  {
                1,              0,              0 
  },
  {
                1,  -0.6344484687,   0.5918263793 
  },
  {
                1,              0,              0 
  }
};
